spring.application.name=hotel-management
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=10781078
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-unknown-properties=false
